create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  email text not null,
  rfid_card text not null,
  photo text not null,
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;

create table public.locations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  ciudad text not null,
  direccion text not null,
  constraint locations_pkey primary key (id)
) TABLESPACE pg_default;

create table public.fingerprints (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  employee_id bigint not null,
  location_id bigint not null,
  constraint fingerprints_pkey primary key (id),
  constraint fingerprints_employee_id_fkey foreign KEY (employee_id) references users (id) on update CASCADE on delete CASCADE,
  constraint fingerprints_location_id_fkey foreign KEY (location_id) references locations (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.access_logs (
  id bigint generated by default as identity not null,
  access_time timestamp with time zone not null default now(),
  employee_id bigint not null,
  location_id bigint not null,
  access_method text not null,
  fingerprint_id bigint null,
  rfid_card_code text null,
  constraint access_logs_pkey primary key (id),
  constraint access_logs_employee_id_fkey foreign KEY (employee_id) references users (id) on update CASCADE on delete CASCADE,
  constraint access_logs_fingerprint_id_fkey foreign KEY (fingerprint_id) references fingerprints (id) on update CASCADE on delete CASCADE,
  constraint access_logs_location_id_fkey foreign KEY (location_id) references locations (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create view public.users_with_last_access_and_location as
select
  u.id,
  u.name,
  u.email,
  u.rfid_card,
  l.name as sede,
  (
    select
      al.access_time
    from
      access_logs al
    where
      al.employee_id = u.id
    order by
      al.access_time desc
    limit
      1
  ) as last_access,
  u.photo
from
  users u
  left join fingerprints f on f.employee_id = u.id
  left join locations l on l.id = f.location_id;